### PR TITLE
Isengard Cleanup

### PR DESCRIPTION
**Pull request by bumpaneer**
Not sure if this will be in time for the repo pull, but some additional cleanup on the Isengard front.  Refactored the shutdown options code to be a bit cleaner.

### CODE REVIEW

**Comment by kib** [comment]
You will need to rebase first and force push to this PR, since you are now including my commit in this pull.

**Comment by kib** [comment]
Not too late; something went wrong with my submission. If you are fast with the rebase I'll include them and bump it to 5.0.1 respectively 4.0.1 and submit those.

**Comment by kib** [comment]
If you fix the rebase issue and force push the PR I can include it.
By the way, this is why you don't PR from the original branch normally. It gets troublesome when someone else modifies that branch. You seem to have commited my commit (did you pull it or something?) instead of rebasing.

**Comment by bumpaneer** [comment]
Whoops, I think I originally cherry picked the addon.xml bump without rebasing, does it look correct now?

**Comment by kib** [comment]
Looking good, i'll do the submit when I get back home in a few hours. Thanks for cleaning it up.

**Pull request merged**
