### PR TITLE
Take 2

### PR DESCRIPTION
**Pull request by dknudsen89**
Hi Kib.
Here's a new PR.
Not sure if I did everything correctly, but I think so. 
If not I can just send you the files.

### CODE REVIEW

**Comment by kib** [comment]
You created a new PR with the same commits in it. This needs to be history rewritten and force pushed.

If you don't know how to do that, I'll cherry pick these changes and pull them in, but it might be nice to take some time to learn git.

Thanks a bunch for the work anyway!

**Comment by dknudsen89** [comment]
Dammit!
If you could cherry pick the changes instead, I'll go away and read up on how github works :)

Sorry for the inconvenience. :)

**Comment by kib** [comment]
No problem, but what you need to do is not hard. It might be more beneficial to explain it :smile: 

Basically you need to rewrite your history. so your own local history looks like only 2 commits, you can then force push that to your repo on github and this pull request will automatically update.

To do that read http://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history
and do the following:
- rewrite the last 6 commits
  use the command: git rebase -i HEAD~6
- remove the first 4 lines (the two commits and their undoing) leaving only 2 lines.
- (optionally) reword the other two lines (put a r in front and rewrite the commit message behind the number)
- save the editor

You will see that your local repo now only has the two last commits in it. Now you want to force push them online. You are forcing it because normally a push does not allow you to rewrite history (it would be bad for people who had a copy of your code!).

Use the command: git push --force origin Helix
If your github repo is called origin, and the branch is called Helix.

After you force push come back here and refresh the page and you will see there are only two commits there. At that point I can just merge it :+1: 

This is also why it is better to do these changes in a seperate branch from your main. While you are working on modifications in your Helix branch (which is a copy of mine), I might make some as well into my Helix branch - I might even edit the same file or the same line - in this case you would have an issue because those changes might not apply anymore and you can't just pull my changes into your own repo because of the conflict. When your changes are in a seperate branch from your main it is easier to rebase that branch on top of your new master after you have had to pull in changes I made. When there is a conflict (we both edited the same line) git has excellent conflict resolution built into the rebase command (see link). This allows multiple people to work on the same project without going mental :ghost: 

Feel free to experiment with this. If all fails - you can always delete your entire fork and refork it from mine. I have already picked the changes and will apply them soon - I'll wait a bit because I'd like to see you do it :exclamation:

**Comment by kib** [comment]
Done. see https://github.com/kib/skin.neon/pull/69

**Pull request closed without merging**
