### PR TITLE
Convert to strings.po translations

### PR DESCRIPTION
**Pull request by bumpaneer**
See: http://forum.xbmc.org/showthread.php?tid=174471

### CODE REVIEW

**Comment by kib** [comment]
I rather want to fix this completely by moving to transifex, see #6

**Comment by kib** [comment]
Please rebase with the additional languages removed and I'll submit the English strings to transifex asap.

**Comment by bumpaneer** [comment]
Before that is done there is quite a bit of cleanup that needs to be done on the strings side.  The initial issue is that the Skin XML Converter by phil65 (http://forum.xbmc.org/showthread.php?tid=132720) expects to have the strings in the .po format.  Once this is done you can use the Check Labels to view all the issues with Untranslated Labels and Unused Strings (there are quite a few in Neon).  Before uploading to Transifex with an incomplete/incorrect strings list, it would probably be best to get the issue fixed first so we get an accurate/complete translation for the other languages.

**Comment by kib** [comment]
In that case please add a commit that removes the other languages and I'll pull it. We can then fix the English.po to be compliant. 
Once that is done bump the skin to repo and submit to transifex.

**Comment by bumpaneer** [comment]
Will close this request.  I have re-factored a fair bit to bring the strings in line and will submit another pull request.

**Comment by kib** [comment]
If you develop stuff like this in a seperate branch and PR from there then you could just force push to your own branch and the pr would update. Very handy!

**Comment by bumpaneer** [comment]
Good to know, I'll keep that in mind for next time.  Thanks!

**Pull request closed without merging**
