### PR TITLE
Fix Shelf view for Albums

### PR DESCRIPTION
**Pull request by bumpaneer**
Animation was causing focus issues.  Its unneeded so it has been removed.

### CODE REVIEW

**Comment by bumpaneer** [comment]
Also fix dark backgrounds for album info

**Comment by bumpaneer** [comment]
The Antipasto font is missing the default less than symbol.  Used U+2039 character instead.  Should fix: http://forum.xbmc.org/showthread.php?tid=200560

**Comment by bumpaneer** [comment]
Song view type should be fixed, see: http://forum.xbmc.org/showthread.php?tid=200559

**Comment by kib** [comment]
Thanks a bunch as usual !

I will submit the addon bump today.

If you want, feel free to work on the Helix branch, it still needs a lot of work.

**Pull request merged**
